[package]
name = "babibapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.55"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.8"
actix-web = "3.3.3"
