[http]
bind = "127.0.0.1"
port = 59172

[database]
name = "babibapp"
user = "babibapp"
password = "password123"
host = "localhost"
pool_size = 5

[token]
secret = "SECRET"
expiration_hours = 24

[root]
email = "root@root"
password = "toor"
expiration_minutes = 30
