[package]
name = "babibapp_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
babibapp_models = { path = "../../models" }
reqwest = { version = "0.11", features = ["json"] }
anyhow = "1.0"
